print("Hello")
print("Welcome", "to", "GfG")
print()
print("How are you doing?")
print("Welcome", end="--")
print("to my house.")
print("25", "08", "2020", sep="/")
print(10, 20, 30, sep="+", end=" ")
print(40, 50)